name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install
        run: yarn install

      - name: Build
        run: |
          yarn lint
          yarn build

      - name: Commit
        env:
          TZ: Asia/Shanghai
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist
          git commit -m ":bento: Build at \
          $(date +"%Y-%m-%d %H:%M") \
          "
          git push
